export const nameLibPolish = {
  signIn: "Zaloguj się",
  username: "Nazwa użytkownika",
  password: "Hasło",
  dontHaveAccount: "Nie masz konta?",
  alreadyHaveAccount: "Masz już konto?",
  register: "Rejestracja",
  signUp: "Zarejestruj się",
  forgotYourPasswordOrWantToChangeIt:
    "Zapomniałeś hasła lub chcesz je zresetować?",
  recoverPassword: "Odzyskaj hasło",
  reEnterPassword: "Powtórz hasło",
  newPassword: "Nowe hasło",
  reEnterNewPassword: "Powtórz nowe hasło",
  passwordRecoveryQuestion: "Pytanie do odzyskiwania hasła",
  haveYouManagedToRecover: "Udało ci się odzyskać konto?",
  didntManageToRecover: "Nie udało się odzyskać konta?",
  favFood: "Jakie jest twoje ulubione jedzenie?",
  firstPetName: "Jakie jest imie twojego pierwszego zwierzątka?",
  startQuiz: "Rozpocznij quiz",
  continueQuiz: "Kontynuuj quiz",
  quizHistory: "Historia quizów",
  flashcards: "Fiszki",
  logout: "Wyloguj się",
  startNewQuiz: "Rozpocznij nowy quiz",
  nextQuestion: "Następne pytanie",
  quizName: "Nazwa quizu",
  dateOfCompletion: "Data ukończenia",
  pathwayScores: "Wyniki ścieżek",
  flashcardCategories: "Kategorie fiszek",
  flashcardCategory: "Kategoria fiszek",
  flashcardCategoryEmpty: "Ta kategoria fiszek jest pusta",
  goBackToCatSelection: "Powrót do kategorii",
  category: "Kategoria",
  flashcardCatOver: "To ostatnia fiszka z kategorii, rozpocząć od nowa?",
  startOver: "Rozpocznij od nowa",
  manual: "Poradnik użytkownika",
  thankYouForCompleting: "Dziękujemy za ukończenie quizu!",
  yourScore: "Twój wynik",
  quizHistoryEmpty: "Wygląda na to że nie ma ukończonych quizów",
  studentCredit: "Zaliczenie",
  teacherPanel: "Panel nauczyciela",
  adminPanel: "Panel administratora",
  enterCreditCode: "Wpisz kod zaliczeniowy tutaj",
  creditCode: "Kod zaliczeniowy",
  addToGroup: "Dodaj do grupy",
  groups: "Grupy",
  createGroup: "Stwórz grupę",
  groupName: "Nazwa grupy",
  createGroupDate: "Ustaw termin końcowy zaliczenia",
  backToTeacherPanel: "Powrót do panelu nauczyciela",
  groupCode: "Kod grupy",
  actions: "Akcje",
  deleteGroup: "Usuń grupę",
  groupDetails: "Szczegóły grupy",
  students: "Studenci",
  downloadGroupScore: "Pobierz wyniki grupy",
  deleteAllStudents: "Usuń wszystkich studentów",
  downloadStudentScore: "Pobierz wyniki",
  deleteStudent: "Usuń",
  details: "Szczegóły",
  delete: "Usuń",
  backToAdminPanel: "Powrót do panelu administratora",
  teachersList: "Lista nauczycieli",
  createTeacher: "Stwórz nauczyciela",
  allUsers: "Wszyscy użytkownicy",
  teachers: "Nauczyciele",
  viewGroups: "Pokaż grupy",
  teacherLogin: "Login nauczyciela",
  teacherPassword: "Hasło nauczyciela",
  teacherPhraseOne: "Odzyskiwanie hasła 1",
  teacherPhraseTwo: "Odzyskiwanie hasła 2",
  adminGroups: "Lista grup",
  teacherName: "Nazwa nauczyciela",
  roles: "Role",
  usernames: "Nazwy użytkownika",
  deleteAllUsers: "Usuń wszystkich użytkowników",
  successfullyAddedToGroup: "Pomyślnie dodano do grupy",
  creditCodeNotFound: "Nie znaleziono grupy z danym kodem",
  groupCreated: "Grupa została utworzona! kod grupy:",
  groupsEmpty: "Wygląda na to że nie ma utworzonych grup...",
  tutorial: "Tutorial",
  tutorialHeader: "Krótka instrukcja obsługiwania dla użytkownika:",
  tutorialBasics: "Podstawowe instrukcje:",
  loading: "Wczytywanie...",
  teacherCreated: "Utworzono nauczyciela",
  disableActionConfirmation: "Wyłączyć zatwierdzanie akcji?",
  areYouSure: "Czy potwierdzasz, że chcesz usunąć dane?",
  no: "Nie",
  yes: "Tak",
  attemptsOver:
    "Wyczerpano limit podejść do quizu (można kontynować podejścia, ale nie zapiszą się w historii)",
  attemptsOverExplanation:
    "(można kontynować podejścia, ale nie zapiszą się w historii)",
  passwordInfo:
    "Haslo co najmniej 8 znakow i maksymalnie 20 1 cyfra 1 duza litera 1 mala litera",
  registrationSuccessfull: "Rejestracja przebiegła pomyślnie",
  recoverySuccessfull: "Wprowadzono nowe hasło",
  usernameRegister: "Nazwa użytkownika to email studenta WUM",
  invalidPassword: "Nieprawidłowy format hasła",
};

export const nameLibEnglish = {
  signIn: "Sign in",
  username: "Username",
  password: "Password",
  dontHaveAccount: "Don't have an account?",
  alreadyHaveAccount: "Already have an account?",
  register: "Register",
  signUp: "Sign up",
  forgotYourPasswordOrWantToChangeIt:
    "Forgot your password or want to change it?",
  recoverPassword: "Recover password",
  reEnterPassword: "Re-enter password",
  newPassword: "New password",
  reEnterNewPassword: "Re-enter new password",
  passwordRecoveryQuestion: "Password recovery question",
  haveYouManagedToRecover: "Have you managed to recover?",
  didntManageToRecover: "Couldn't recover?",
  favFood: "What's your favorite food?",
  firstPetName: "What's your first pet's name?",
  startQuiz: "Start quiz",
  continueQuiz: "Continue quiz",
  quizHistory: "Quiz history",
  flashcards: "Flashcards",
  logout: "Logout",
  startNewQuiz: "Start new quiz",
  nextQuestion: "Next question",
  quizName: "Quiz name",
  dateOfCompletion: "Date of completion",
  pathwayScores: "Pathway scores",
  flashcardCategories: "Flashcard categories",
  flashcardCategory: "Flashcard category",
  flashcardCategoryEmpty: "This flashcard category is empty",
  goBackToCatSelection: "Go back to category selection",
  category: "Categories",
  flashcardCatOver:
    "This flashcard category is finished, do you want to start it again?",
  startOver: "Start over",
  manual: "User manual",
  thankYouForCompleting: "Thank you for completing the quiz!",
  yourScore: "Your score",
  quizHistoryEmpty: "Looks like the quiz history is empty",
  studentCredit: "Credit",
  teacherPanel: "Teacher panel",
  adminPanel: "Admin panel",
  enterCreditCode: "Enter credit code here",
  creditCode: "Credit code",
  addToGroup: "Add to group",
  groups: "Groups",
  createGroup: "Create group",
  groupName: "Group name",
  createGroupDate: "Set deadline for credit",
  backToTeacherPanel: "Back to teacher panel",
  groupCode: "Group code",
  actions: "Actions",
  deleteGroup: "Delete group",
  groupDetails: "Group details",
  students: "Students",
  downloadGroupScore: "Download group score",
  deleteAllStudents: "Delete all students",
  downloadStudentScore: "Download score",
  deleteStudent: "Delete",
  details: "Details",
  delete: "Delete",
  backToAdminPanel: "Back to admin panel",
  teachersList: "Teachers list",
  createTeacher: "Create teacher",
  allUsers: "All users",
  teachers: "Teachers",
  viewGroups: "Show groups",
  teacherLogin: "Teacher login",
  teacherPassword: "Teacher password",
  teacherPhraseOne: "Password recovery 1",
  teacherPhraseTwo: "Password recovery 2",
  adminGroups: "Groups list",
  teacherName: "Teacher username",
  roles: "Roles",
  usernames: "Usernames",
  deleteAllUsers: "Delete all users",
  successfullyAddedToGroup: "Succesfully added to group",
  creditCodeNotFound: "Could not find group with the given code",
  groupsEmpty: "Looks like there are no created groups yet...",
  tutorial: "Tutorial",
  tutorialHeader: "A short manual for the user:",
  loading: "Loading...",
  teacherCreated: "Teacher created",
  disableActionConfirmation: "Disable action confirmation?",
  areYouSure: "Do you confirm you want to delete the data?",
  no: "No",
  yes: "Yes",
  attemptsOver:
    "You have reached the limit of quiz attempts (you may continue solving the quiz but it won't be saved to history)",
  attemptsOverExplanation:
    "(you may continue solving the quiz but it won't be saved to history)",
  passwordInfo:
    " Password is at least 8 characters and maximum of 20, 1 number 1 uppercase 1 lowercase",
  registrationSuccessfull: "Registration successfull",
  recoverySuccessfull: "New password is entered",
  usernameRegister: "Username is a WUM student's mail",
  invalidPassword: "Invalid password format",
};

export const LANGUAGE_CONFIG = {
  availableLanguages: {
    polish: nameLibPolish,
    english: nameLibEnglish,
  },
};
