spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 20
      max-idle: 10
      remove-abandoned: true
  jpa:
    hibernate:
      ddl-auto: create
app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ
    refreshTokenExpTime: 86400000
    jwtExpirationExpTime: 3600000
server:
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
#  port: ${PORT:5000}